on: push

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - name: "Print current version of Xcode"
        run: xcodebuild -version
      - uses: actions/checkout@v2
      - name: "Build"
        run: swift build
      - name: "Test"
        run: swift test
